config/routes.rb
SAA::Application.routes.draw do
  
  resources :nodes
  root 'nodes#index'
  
  get 'signup', to: 'users#new'
  get 'login', to: 'session#new'
  get 'logout', to: 'session#destroy'
  
  resources :users
  resources :session

end

app/models/node.rb
class Node < ActiveRecord::Base
	has_ancestry :orphan_strategy => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password
	
	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email
	
	before_save :encrypt_password

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end

	def authenticate_password(password)
		password_hash == BCrypt::Engine.hash_secret(password, password_salt)
	end

	def self.create_user(params)
		user = User.new(:name => params[:user][:name], :email => params[:user][:email], :password => params[:user][:password])
		status = user.save
		return user, status
	end

	def self.authenticate_user(email, password, options={})
		user = find_by_email(email)
		if user && user.authenticate_password(password)
			user
		else
			nil
		end
	end

	def self.find_by_email(email)
		User.where("email=?",email).last
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
	layout "application"

	protect_from_forgery with: :exception

	helper_method :current_user

	before_action :authenticate

	def authenticate
		if current_user.nil?
			redirect_to_login
		end
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def redirect_to_login
	    if request.xhr?
	      render js: "window.location.reload();"
	    else
	       redirect_to login_path   
	    end
	end 

	
	def default_paginate_options
		{:per_page => 10, :page => params[:page] || 1}
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def hall
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.where("ancestry is null")
  end

  # POST /nodes
  # POST /nodes.json
  def create
    if(node_params[:parent_id])
      parent = Node.find(node_params[:parent_id])
      @node = Node.create!(:name => node_params[:name], :parent => parent)
    else
      @node = Node.new(node_params)
    end
    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :json => {:node_id => @node.id} }
      else
        format.html { render :new }
        format.json { render :json => {:errors => @node.errors} }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :json => {:node_id => @node.id} }
      else
        format.html { render :edit }
        format.json { render :json => {:errors => @node.errors} }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:name,:parent_id, :id)
      # params.require(:node,:parent_id).permit(:name)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	
	skip_filter :authenticate, :only => [:create, :new]

	def new
		
	end

	def create
		@user = User.authenticate_user(params[:email], params[:password])
		if @user
			session[:user_id] = @user.id
			redirect_to root_path, notice: "Logged in!!"
		else
			redirect_to login_path, notice: "Invalid credentials"
		end
	end

	def destroy
		session[:user_id] = nil
		reset_session
		redirect_to login_path, notice: "Logged out!!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	skip_filter :authenticate, :only => [:create, :new]

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user, status = User.create_user(params)
		if status
			session[:user_id] = @user.id
			redirect_to root_path, notice: "Successfully signed up."
		else
			flash[:notice] = @user.errors.full_messages
			redirect_to new_user_path
		end
	end

	def show
		respond_to do |format|
			format.js{
				render :partial=>'show.js.erb'
			}
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/home/hall.html.erb
<h3>Welcome to <%=current_user.name%></h3>

app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title><%=APP_NAME%></title>
	<%= stylesheet_link_tag "application"%>
  <%= javascript_include_tag "application"%>
	<%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body style='overflow: auto;'>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <%= render :partial => "shared/top_panel.html.erb"%>
  </div>
</nav>
<div class="container-fluid"  style='margin-top: 60px;overflow: auto;'>
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <%= render :partial => "shared/left_panel.html.erb"%>
        </div>
        <div class="col-sm-9 col-md-10 main">
          <div id="notify_me"></div>
          <div id="centercol">
            <div id="flash_me">
              <%= render 'shared/flash_messages' if !flash.empty? %>
            </div>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
</body>
</html>

app/views/layouts/application.html.erb
<%= render :partial => "layouts/application.html.erb"%>

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/_node.html.erb
<div class="easy-tree">
	<ul>
		<% nodes.each do |node| %>
			<%= render :partial => "node_nested.html.erb", :locals =>{:node => node}%>
		<%end%>
	</ul>
</div>
<script type="text/javascript">
    (function ($) {
        $('.easy-tree').EasyTree({
            addable: true,
            editable: true,
            deletable: true
        });
    })(jQuery)
</script>

app/views/nodes/_node_nested.html.erb
<li data-node-id='<%=node.id%>'><%= node.name%>
	<%if node.has_children? %>
		<ul>
			<%node.children.each do |child|%>
				<%= render :partial => "node_nested.html.erb", :locals =>{:node => child}%>
			<%end%>
		</ul>
	<%end%>
</li>

app/views/nodes/edit.html.erb
<h1>Editing Node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid" >
  <div class="row">
    <div class="col-md-11">
      <h3 class="text-success">Manage Nodes</h3>
      <%= render :partial => "node.html.erb", :locals =>{:nodes => @nodes}%>
    </div>
    <!-- <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @nodes.each do |node| %>
          <tr>
            <td><%= node.name %></td>
            <td><%= link_to 'Show', node %></td>
            <td><%= link_to 'Edit', edit_node_path(node) %></td>
            <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div> -->
  </div>
</div>

app/views/nodes/new.html.erb
<h1>New Node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @node.name %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>

app/views/session/new.html.erb
<div class="container-fluid" style="width:400px;float:left">
	<h2 class="sub-header">Login</h2></br>
	<%= form_tag({:controller => "session", :action => "create"}) do %>
		<div class="form-group">
			<label>Email</label>
			<input type="text" name="email" class="form-control" />
		</div>

		<div class="form-group">
			<label>Password</label>
			<input type="password" name="password" class="form-control" />
		</div>
		<input type="submit" value="Login" class="btn btn-primary"/>
	<% end %>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, messages| %>
	<div class="alert alert-success ">
		<%	
			messages = messages.is_a?(String) ? [messages] : messages	
		%>
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		
		<%messages.each do |message|%>
			<%= content_tag(:div, message, :class => "flash #{key}") %>
		<%end%>
		
	</div>
<% end %>

app/views/shared/_left_panel.html.erb
<!-- _left_panel.html.erb -->
<%if current_user%>
<ul class="nav nav-sidebar">
	<li class="active">
		<%=link_to "Home", root_path%>
	</li>
</ul>
<%end%>

app/views/shared/_noty_messages.html.erb
<%
	@noty_type = @noty_type||"success"
	@noty_layout = @noty_layout||"topCenter"
	@noty_timeout = @noty_timeout||2000
%>
<%if @noty_text%>
	<script type="text/javascript">
		try{
			generate(<%=@noty_text%>, <%=@noty_type%>, <%=@noty_layout%>, <%=@noty_timeout%>)
		}catch(e){alert(e)}
	</script>
<%end%>

app/views/shared/_noty_messages.js.erb
$('#notify_me').html("<%= escape_javascript (render :partial=>'shared/noty_messages.html.erb') %>");

app/views/shared/_top_panel.html.erb
<!-- _top_panel.html.erb -->
<div class="navbar-header">
  <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%=link_to "#{APP_NAME} <span style='font-size:50%'>#{APP_TAGLINE}</span>".html_safe, root_path, {:class => "navbar-brand"}%>
</div>
<div class="navbar-collapse collapse" id="navbar">
  <ul class="nav navbar-nav navbar-right">
      <%if current_user%>
        <li>
          <%= link_to "#{current_user.name}", {:controller => "users", :action => "show", :id => current_user.id}, {:remote => true}%>
        </li>
        <li><%= link_to "Logout", {:controller => "session", :action => "destroy", :id => current_user.id}, method: :delete%></li>
      <%else%>
        <li><a href="#">Guest</a></li>
        <li><%= link_to "Login", {:controller => "session", :action => "new"}%></li>
        <li><%= link_to "Sign up", {:controller => "users", :action => "new"}%></li>
      <%end%>
  </ul>
<!--   <form class="navbar-form navbar-right">
    <input type="text" placeholder="Search..." class="form-control">
  </form> -->
 
</div>

app/views/users/_show.html.erb
<!-- _show.html.erb -->
<div class="container-fluid" style="width:400px;float:left">
	<h2 class="sub-header">Profile</h2></br>
	<p>
	  <strong>Name:</strong>
	  <%= current_user.name %>
	</p>

	<p>
	  <strong>Email:</strong>
	  <%= current_user.email %>
	</p>
</div>

app/views/users/_show.js.erb
$('#centercol').html("<%= escape_javascript (render :partial=>'show.html.erb') %>");

app/views/users/index.html.erb
<h1>Listing Users</h1>
<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'Entries', entries_path, {:class => "btn btn-default"} %>

app/views/users/new.html.erb
<div class="container-fluid" style="width:400px;float:left">
	<h2 class="sub-header">Sign up</h2></br>
	<%= form_for @user do |f|%>
		<div class="form-group">
			<%=f.label :name%>
			<%=f.text_field :name, {:class=>"form-control"}%>
		</div>

		<div class="form-group">
			<%=f.label :email%>
			<%=f.text_field :email, {:class=>"form-control"}%>
		</div>

		<div class="form-group">
			<%=f.label :password%>
			<%=f.text_field :password, {:class=>"form-control", :type => "password"}%>
		</div>

		<div class="form-group">
			<%=f.label :password_confirmation%>
			<%=f.text_field :password_confirmation, {:class=>"form-control", :type => "password"}%>
		</div>

		<%= f.submit "Submit", :value => "Sign up", :class => "btn btn-primary"%>
	<% end %>
</div>
</div>